apiVersion: v1
kind: Service
metadata:
  name: student-id-service
spec:
  type: NodePort
  selector:
    app: student-id-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080